#!/usr/bin/env node

/**
 * NexaFlow Setup Script
 * Helps set up the Supabase backend quickly
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🚀 NexaFlow Setup Wizard\n');

async function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

async function main() {
  try {
    console.log('This wizard will help you set up NexaFlow with Supabase.\n');
    
    // Get Supabase credentials
    const supabaseUrl = await askQuestion('Enter your Supabase Project URL: ');
    const supabaseKey = await askQuestion('Enter your Supabase Anon Key: ');
    
    if (!supabaseUrl || !supabaseKey) {
      console.log('❌ Both Supabase URL and Anon Key are required.');
      process.exit(1);
    }
    
    // Validate URL format
    if (!supabaseUrl.includes('supabase.co')) {
      console.log('❌ Invalid Supabase URL format. It should look like: https://your-project.supabase.co');
      process.exit(1);
    }
    
    // Create .env.local file
    const envContent = `# NexaFlow Environment Configuration
# Generated by setup script

# Supabase Configuration
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseKey}

# Application Mode
VITE_DEMO_MODE=true

# Application URLs
VITE_APP_URL=http://localhost:5173
VITE_API_URL=http://localhost:3001/api

# File Storage
VITE_MAX_FILE_SIZE=50MB
VITE_ALLOWED_FILE_TYPES=.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.gif,.zip

# Notification Settings
VITE_ENABLE_EMAIL_NOTIFICATIONS=true
VITE_ENABLE_WHATSAPP_NOTIFICATIONS=false
VITE_ENABLE_PUSH_NOTIFICATIONS=true

# Security
VITE_SESSION_TIMEOUT=24h

# Analytics
VITE_ENABLE_ANALYTICS=true
`;
    
    fs.writeFileSync('.env.local', envContent);
    console.log('✅ Created .env.local file');
    
    // Show next steps
    console.log('\n🎉 Setup complete! Next steps:\n');
    console.log('1. Set up your Supabase database:');
    console.log('   - Open your Supabase project dashboard');
    console.log('   - Go to SQL Editor');
    console.log('   - Copy and run the contents of supabase-schema.sql\n');
    
    console.log('2. Create demo users in Supabase Authentication > Users:');
    console.log('   - admin@nexaflow.com (password: demo123)');
    console.log('   - pm@nexaflow.com (password: demo123)');
    console.log('   - sarah@nexaflow.com (password: demo123)');
    console.log('   - alex@nexaflow.com (password: demo123)');
    console.log('   - client@nexaflow.com (password: demo123)\n');
    
    console.log('3. Add sample data:');
    console.log('   - Update user IDs in supabase-sample-data.sql');
    console.log('   - Run the sample data script in SQL Editor\n');
    
    console.log('4. Start the development server:');
    console.log('   npm run dev\n');
    
    console.log('📖 For detailed instructions, see DEPLOYMENT.md');
    console.log('🆘 Need help? Check README.md or create an issue\n');
    
  } catch (error) {
    console.error('❌ Setup failed:', error.message);
    process.exit(1);
  } finally {
    rl.close();
  }
}

main();